spring.datasource.url=jdbc:postgresql://localhost:5435/tg_for_user
spring.datasource.username=tg_bot

spring.liquibase.change-log=classpath:liquibase/changelog-master.yaml
spring.profiles.active=local
server.port=8095
